
import React, { useState, useEffect, useRef, useCallback } from 'react';
import Sidebar from './components/Sidebar';
import Player from './components/Player';
import MoodSync from './components/MoodSync';
import { AppSection, Song } from './types';
import { MOCK_SONGS } from './constants';
import { Play, Shuffle, Search, Bell, Settings, Heart, MoreHorizontal, Sparkles, Wand2, MessageCircle, Youtube, Disc, Plus, Loader2, Database, Terminal, Copy, Check } from 'lucide-react';
import { toggleLikeInDB, fetchLikedSongs, fetchSongsPaginated, addSongToLibrary } from './services/supabaseService';
import { supabase } from './services/supabaseClient';
import { getYouTubeVideoData } from './services/youtubeService';
import { MusicProvider, useMusic } from './context/MusicContext';

const PAGE_SIZE = 8;

const AppContent: React.FC = () => {
  const [section, setSection] = useState<AppSection>(AppSection.HOME);
  const [showMoodSync, setShowMoodSync] = useState(false);
  const [likedSongIds, setLikedSongIds] = useState<Set<string>>(new Set());
  const [songs, setSongs] = useState<Song[]>([]);
  const [user, setUser] = useState<any>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [isSearching, setIsSearching] = useState(false);
  const [searchResults, setSearchResults] = useState<Song[]>([]);
  const [dbErrorCode, setDbErrorCode] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  
  // Infinity Scroll States
  const [page, setPage] = useState(0);
  const [hasMore, setHasMore] = useState(true);
  const [isFetchingMore, setIsFetchingMore] = useState(false);
  const observerTarget = useRef<HTMLDivElement>(null);

  const { setCurrentSong, currentSong, isPlaying } = useMusic();

  const SQL_SCHEMA = `-- 1. Create the 'songs' table
CREATE TABLE songs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  artist TEXT,
  album TEXT,
  youtube_id TEXT,
  cover_url TEXT,
  duration TEXT,
  genre TEXT,
  plays_count BIGINT DEFAULT 0
);

-- 2. Create the 'likes' table
CREATE TABLE likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  user_id UUID REFERENCES auth.users(id),
  song_id BIGINT REFERENCES songs(id) ON DELETE CASCADE,
  UNIQUE(user_id, song_id)
);`;

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setUser(session?.user ?? null);
      if (session?.user) {
        fetchLikedSongs(session.user.id)
          .then(setLikedSongIds)
          .catch(err => console.error("Initial likes fetch failed:", err.message));
      }
    });

    loadInitialSongs();
  }, []);

  const loadInitialSongs = async () => {
    try {
      const data = await fetchSongsPaginated(0, PAGE_SIZE - 1);
      if (data && data.length > 0) {
        setSongs(data);
        setDbErrorCode(null);
        if (data.length < PAGE_SIZE) setHasMore(false);
      } else {
        setSongs(MOCK_SONGS.map(s => ({...s, youtubeId: 'dQw4w9WgXcQ'})));
        setHasMore(false);
      }
    } catch (err: any) {
      if (err.code === 'PGRST205') {
        setDbErrorCode('PGRST205');
      }
      setSongs(MOCK_SONGS.map(s => ({...s, youtubeId: 'dQw4w9WgXcQ'})));
      setHasMore(false);
    }
  };

  const loadMoreSongs = useCallback(async () => {
    if (isFetchingMore || !hasMore || dbErrorCode) return;
    
    setIsFetchingMore(true);
    const nextPage = page + 1;
    const from = nextPage * PAGE_SIZE;
    const to = from + PAGE_SIZE - 1;

    try {
      const newData = await fetchSongsPaginated(from, to);
      if (newData.length > 0) {
        setSongs(prev => [...prev, ...newData]);
        setPage(nextPage);
        if (newData.length < PAGE_SIZE) setHasMore(false);
      } else {
        setHasMore(false);
      }
    } catch (err) {
      console.error("Error loading more songs:", err);
      setHasMore(false);
    } finally {
      setIsFetchingMore(false);
    }
  }, [page, hasMore, isFetchingMore, dbErrorCode]);

  useEffect(() => {
    const observer = new IntersectionObserver(
      entries => {
        if (entries[0].isIntersecting && hasMore && !isFetchingMore) {
          loadMoreSongs();
        }
      },
      { threshold: 0.1 }
    );

    if (observerTarget.current) {
      observer.observe(observerTarget.current);
    }

    return () => observer.disconnect();
  }, [loadMoreSongs, hasMore, isFetchingMore]);

  const handleCopySql = () => {
    navigator.clipboard.writeText(SQL_SCHEMA);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchQuery.trim()) return;

    setIsSearching(true);
    setSection(AppSection.SEARCH);
    
    try {
      const localMatches = songs.filter(s => 
        s.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
        s.artist.toLowerCase().includes(searchQuery.toLowerCase())
      );

      const ytData = await getYouTubeVideoData(searchQuery);
      const results: Song[] = [...localMatches];
      
      if (ytData) {
        const alreadyFound = localMatches.some(m => m.youtubeId === ytData.videoId);
        if (!alreadyFound) {
          results.push({
            id: `yt-${ytData.videoId}`,
            title: ytData.title,
            artist: 'YouTube Discovery',
            album: 'Single',
            coverUrl: ytData.thumbnailUrl,
            duration: '0:00',
            plays: '0',
            youtubeId: ytData.videoId
          });
        }
      }
      setSearchResults(results);
    } catch (err: any) {
      console.error("Search error:", err.message);
    } finally {
      setIsSearching(false);
    }
  };

  const handleAddToLibrary = async (song: Song) => {
    try {
      await addSongToLibrary({
        title: song.title,
        artist: song.artist === 'YouTube Discovery' ? '' : song.artist,
        youtubeId: song.youtubeId,
        coverUrl: song.coverUrl
      });
      // Reset pagination and reload to show new item
      setPage(0);
      setHasMore(true);
      loadInitialSongs();
      alert(`${song.title} added to your library!`);
    } catch (err: any) {
      alert(`Error: ${err.message}. Make sure your tables are created in Supabase.`);
    }
  };

  const toggleLike = async (id: string) => {
    const isLiked = likedSongIds.has(id);
    setLikedSongIds(prev => {
      const next = new Set(prev);
      if (isLiked) next.delete(id);
      else next.add(id);
      return next;
    });

    if (user) {
      try {
        await toggleLikeInDB(user.id, id, isLiked);
      } catch (err: any) {
        setLikedSongIds(prev => {
          const next = new Set(prev);
          if (isLiked) next.add(id);
          else next.delete(id);
          return next;
        });
      }
    } else {
      alert("Sign in to sync likes across devices!");
    }
  };

  const renderHome = () => (
    <>
      {dbErrorCode === 'PGRST205' && (
        <div className="mb-12 bg-zinc-900/50 backdrop-blur-xl border border-yellow-500/20 rounded-3xl overflow-hidden animate-in slide-in-from-top-4 duration-500">
          <div className="p-6 border-b border-white/5 flex items-center justify-between">
            <div className="flex items-center gap-4 text-yellow-500">
              <Database className="w-6 h-6" />
              <div>
                <h3 className="font-bold">Database Setup Required</h3>
                <p className="text-zinc-400 text-sm">The 'songs' table was not found in your Supabase project.</p>
              </div>
            </div>
            <button 
              onClick={handleCopySql}
              className="flex items-center gap-2 bg-white/5 hover:bg-white/10 px-4 py-2 rounded-xl text-sm transition-all"
            >
              {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
              {copied ? 'Copied' : 'Copy Schema SQL'}
            </button>
          </div>
          <div className="p-6 bg-black/40 relative">
            <div className="flex items-center gap-2 text-xs font-mono text-zinc-500 mb-3">
              <Terminal className="w-3 h-3" />
              PASTE THIS INTO SUPABASE SQL EDITOR
            </div>
            <pre className="text-xs font-mono text-zinc-300 overflow-x-auto p-4 bg-zinc-900/50 rounded-xl leading-relaxed">
              {SQL_SCHEMA}
            </pre>
            <p className="mt-4 text-xs text-zinc-500 leading-relaxed">
              Once you've run the SQL above, refresh this page to start using your persistent library.
            </p>
          </div>
        </div>
      )}

      <section className="relative h-[450px] rounded-3xl overflow-hidden mb-12 group">
        <img 
          src={songs[0]?.coverUrl || "https://images.unsplash.com/photo-1493225255756-d9584f8606e9?auto=format&fit=crop&q=80&w=2000"} 
          className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-1000"
          alt="Featured artist"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black via-black/40 to-transparent"></div>
        <div className="absolute bottom-12 left-12 right-12 flex flex-col items-start gap-4">
          <div className="flex items-center gap-2 bg-white/10 backdrop-blur-md px-3 py-1 rounded-full border border-white/10">
            <Sparkles className="w-4 h-4 text-[#ff4b5c]" />
            <span className="text-xs font-bold uppercase tracking-widest">Featured Track</span>
          </div>
          <h2 className="text-7xl font-black tracking-tighter drop-shadow-2xl">{songs[0]?.title || 'Resonate'}</h2>
          <p className="text-2xl text-white/80 font-medium mb-4">{songs[0]?.artist || 'Listen to your vibes'}</p>
          <div className="flex items-center gap-4">
            <button 
              onClick={() => songs[0] && setCurrentSong(songs[0])}
              className="bg-white text-black px-10 py-4 rounded-full font-bold flex items-center gap-3 hover:scale-105 active:scale-95 transition-all shadow-xl shadow-white/5"
            >
              <Play className="w-5 h-5 fill-black" />
              Play Now
            </button>
            <button 
              onClick={() => setShowMoodSync(true)}
              className="bg-gradient-to-r from-[#ff4b5c]/20 to-[#ff1744]/20 backdrop-blur-xl border border-[#ff4b5c]/30 px-6 py-4 rounded-full font-bold flex items-center gap-3 transition-all"
            >
              <Wand2 className="w-5 h-5 text-[#ff4b5c]" />
              Mood-Sync
            </button>
          </div>
        </div>
      </section>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
        <div className="lg:col-span-2">
          <h3 className="text-2xl font-bold mb-8">Quick Picks</h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-x-6 gap-y-10">
            {songs.map((song, index) => (
              <div key={`${song.id}-${index}`} className="group cursor-pointer animate-in fade-in slide-in-from-bottom-2 duration-700 fill-mode-both" style={{ animationDelay: `${(index % PAGE_SIZE) * 50}ms` }}>
                <div 
                  onClick={() => setCurrentSong(song)}
                  className="aspect-square rounded-2xl overflow-hidden mb-4 relative shadow-2xl"
                >
                  <img src={song.coverUrl} className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500" alt={song.title} />
                  <div className={`absolute inset-0 bg-black/40 flex items-center justify-center transition-opacity ${currentSong?.id === song.id ? 'opacity-100' : 'opacity-0 group-hover:opacity-100'}`}>
                    <div className="w-12 h-12 bg-white rounded-full flex items-center justify-center scale-90 group-hover:scale-100 transition-transform">
                      {currentSong?.id === song.id && isPlaying ? <Loader2 className="animate-spin text-black w-6 h-6" /> : <Play className="w-5 h-5 text-black fill-black ml-1" />}
                    </div>
                  </div>
                </div>
                <h4 className="font-bold truncate group-hover:text-[#ff4b5c] transition-colors">{song.title}</h4>
                <p className="text-zinc-500 text-sm truncate">{song.artist}</p>
              </div>
            ))}
          </div>

          {/* Infinity Scroll Trigger */}
          <div ref={observerTarget} className="h-40 flex items-center justify-center w-full mt-10">
            {isFetchingMore && (
              <div className="flex flex-col items-center gap-4">
                <Loader2 className="w-8 h-8 animate-spin text-[#ff4b5c]" />
                <p className="text-zinc-500 text-xs font-medium uppercase tracking-widest">Discovering more tracks...</p>
              </div>
            )}
            {!hasMore && songs.length > PAGE_SIZE && (
              <div className="text-zinc-600 text-sm font-medium border-t border-white/5 w-full pt-10 text-center">
                You've reached the end of the collection.
              </div>
            )}
          </div>
        </div>

        <div className="space-y-12 shrink-0">
          <div className="bg-zinc-900/30 border border-white/5 rounded-3xl p-6 sticky top-8">
            <h3 className="text-xl font-bold mb-6">Liked Songs</h3>
            <div className="space-y-1">
              {songs.filter(s => likedSongIds.has(s.id)).slice(0, 10).map(song => (
                <div key={song.id} className="flex items-center gap-4 p-2 rounded-xl hover:bg-white/5 group transition-colors">
                  <img src={song.coverUrl} className="w-10 h-10 rounded-lg object-cover" alt={song.title} />
                  <div className="flex-1 overflow-hidden cursor-pointer" onClick={() => setCurrentSong(song)}>
                    <p className="text-sm font-semibold truncate group-hover:text-[#ff4b5c] transition-colors">{song.title}</p>
                    <p className="text-xs text-zinc-500 truncate">{song.artist}</p>
                  </div>
                  <button onClick={() => toggleLike(song.id)}>
                    <Heart className="w-4 h-4 text-[#ff4b5c] fill-[#ff4b5c]" />
                  </button>
                </div>
              ))}
              {likedSongIds.size === 0 && <p className="text-zinc-600 text-sm py-4">No favorites yet.</p>}
            </div>
          </div>
        </div>
      </div>
    </>
  );

  const renderSearch = () => (
    <div className="space-y-8 animate-in fade-in slide-in-from-top-4 duration-500">
      <div className="flex items-center justify-between">
        <h2 className="text-3xl font-bold">Search Results {searchQuery && `for "${searchQuery}"`}</h2>
        {isSearching && <Loader2 className="animate-spin text-[#ff4b5c] w-6 h-6" />}
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {searchResults.map((song) => (
          <div key={song.id} className="bg-zinc-900/40 p-4 rounded-2xl border border-white/5 group hover:border-white/10 transition-all">
            <div className="aspect-square rounded-xl overflow-hidden mb-4 relative shadow-xl">
              <img src={song.coverUrl} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" alt={song.title} />
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 flex items-center justify-center gap-3 transition-opacity">
                <button 
                  onClick={() => setCurrentSong(song)}
                  className="w-12 h-12 bg-white rounded-full flex items-center justify-center hover:scale-110 active:scale-95 transition-all shadow-xl"
                >
                  <Play className="w-5 h-5 text-black fill-black ml-1" />
                </button>
                {song.artist === 'YouTube Discovery' && (
                  <button 
                    onClick={() => handleAddToLibrary(song)}
                    className="w-12 h-12 bg-[#ff4b5c] rounded-full flex items-center justify-center hover:scale-110 active:scale-95 transition-all shadow-xl shadow-red-500/20"
                    title="Add to Library"
                  >
                    <Plus className="w-6 h-6 text-white" />
                  </button>
                )}
              </div>
            </div>
            <h4 className="font-bold truncate group-hover:text-[#ff4b5c] transition-colors">{song.title}</h4>
            <p className="text-zinc-500 text-sm truncate">{song.artist}</p>
          </div>
        ))}
        {!isSearching && searchResults.length === 0 && (
          <div className="col-span-full py-20 text-center text-zinc-600 italic">
            No results found. Try searching for an artist or song.
          </div>
        )}
      </div>
    </div>
  );

  return (
    <div className="flex h-screen w-full bg-[#09090b] text-white selection:bg-[#ff4b5c]/30">
      <Sidebar currentSection={section} onSectionChange={setSection} />

      <main className="flex-1 flex flex-col relative overflow-hidden">
        <header className="h-20 flex items-center justify-between px-8 z-20 shrink-0">
          <form onSubmit={handleSearch} className="flex-1 max-w-xl">
            <div className="relative group">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-500 group-focus-within:text-[#ff4b5c] transition-colors" />
              <input 
                type="text" 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search artists, songs or paste YouTube link"
                className="w-full bg-zinc-900/50 border border-white/5 rounded-full py-2.5 pl-12 pr-4 text-sm focus:outline-none focus:border-white/10 focus:bg-zinc-900 transition-all placeholder:text-zinc-600"
              />
            </div>
          </form>
          <div className="flex items-center gap-6">
            <button className="text-zinc-400 hover:text-white transition-colors relative">
              <Bell className="w-5 h-5" />
              <span className="absolute top-0 right-0 w-2 h-2 bg-[#ff4b5c] rounded-full"></span>
            </button>
            <button className="text-zinc-400 hover:text-white transition-colors"><Settings className="w-5 h-5" /></button>
            <div className="h-8 w-[1px] bg-white/10 mx-2"></div>
            <div className="flex items-center gap-3 bg-white/5 px-1.5 pr-4 py-1.5 rounded-full border border-white/5 hover:bg-white/10 transition-colors cursor-pointer">
              <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-indigo-500 to-pink-500 overflow-hidden shadow-lg border border-white/10">
                <img src={user?.user_metadata?.avatar_url || "https://picsum.photos/id/64/100/100"} className="w-full h-full object-cover" alt="User avatar" />
              </div>
              <span className="text-sm font-medium">{user?.email?.split('@')[0] || "Guest User"}</span>
            </div>
          </div>
        </header>

        <div className="flex-1 overflow-y-auto px-8 pb-32 no-scrollbar">
          {section === AppSection.HOME ? renderHome() : renderSearch()}
        </div>

        <div className="fixed bottom-0 left-0 right-0 z-50">
          <Player />
        </div>
      </main>

      {showMoodSync && <MoodSync onClose={() => setShowMoodSync(false)} />}
    </div>
  );
};

const App: React.FC = () => {
  return (
    <MusicProvider>
      <AppContent />
    </MusicProvider>
  );
};

export default App;
